/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 19:34:30 2017. */

#ifndef PB_ALTERMASTERPUSH_PB_H_INCLUDED
#define PB_ALTERMASTERPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _AlterMasterPush {
    int32_t newMasterId;
/* @@protoc_insertion_point(struct:AlterMasterPush) */
} AlterMasterPush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define AlterMasterPush_init_default             {0}
#define AlterMasterPush_init_zero                {0}

/* Field tags (for use in manual encoding/decoding) */
#define AlterMasterPush_newMasterId_tag          1

/* Struct field encoding specification for nanopb */
extern const pb_field_t AlterMasterPush_fields[2];

/* Maximum encoded size of messages (where known) */
#define AlterMasterPush_size                     11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ALTERMASTERPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
