/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Thu Jun 22 20:37:09 2017. */

#ifndef PB_CONNECTRESP_PB_H_INCLUDED
#define PB_CONNECTRESP_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ConnectResp {
    int32_t state;
    char msg[64];
    char uuid[64];
    bool has_masterId;
    int32_t masterId;
    char version[64];
    bool has_versionCode;
    int32_t versionCode;
    char nickname[64];
/* @@protoc_insertion_point(struct:ConnectResp) */
} ConnectResp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ConnectResp_init_default                 {0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define ConnectResp_init_zero                    {0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ConnectResp_state_tag                    1
#define ConnectResp_msg_tag                      2
#define ConnectResp_uuid_tag                     3
#define ConnectResp_masterId_tag                 4
#define ConnectResp_version_tag                  5
#define ConnectResp_versionCode_tag              6
#define ConnectResp_nickname_tag                 7

/* Struct field encoding specification for nanopb */
extern const pb_field_t ConnectResp_fields[8];

/* Maximum encoded size of messages (where known) */
/* ConnectResp_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CONNECTRESP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
