/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Wed Jul 12 20:26:22 2017. */

#ifndef PB_DISCONNECTRESP_PB_H_INCLUDED
#define PB_DISCONNECTRESP_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _DisconnectResp {
    int32_t state;
    char msg[64];
/* @@protoc_insertion_point(struct:DisconnectResp) */
} DisconnectResp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define DisconnectResp_init_default              {0, {{NULL}, NULL}}
#define DisconnectResp_init_zero                 {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define DisconnectResp_state_tag                 1
#define DisconnectResp_msg_tag                   2

/* Struct field encoding specification for nanopb */
extern const pb_field_t DisconnectResp_fields[3];

/* Maximum encoded size of messages (where known) */
/* DisconnectResp_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DISCONNECTRESP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
