/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sat Sep  9 02:25:20 2017. */

#ifndef PB_HWADDVOICEPUSH_PB_H_INCLUDED
#define PB_HWADDVOICEPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwAddVoicePush {
    int32_t voiceIds;
/* @@protoc_insertion_point(struct:HwAddVoicePush) */
} HwAddVoicePush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwAddVoicePush_init_default              {{{NULL}, NULL}}
#define HwAddVoicePush_init_zero                 {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwAddVoicePush_voiceIds_tag              1

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwAddVoicePush_fields[2];

/* Maximum encoded size of messages (where known) */
/* HwAddVoicePush_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWADDVOICEPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
