/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon Jul 17 01:35:53 2017. */

#ifndef PB_HWADDCUSTOMVOICEPUSH_PB_H_INCLUDED
#define PB_HWADDCUSTOMVOICEPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwAddCustomVoicePush {
    pb_callback_t objVoice;
/* @@protoc_insertion_point(struct:HwAddCustomVoicePush) */
} HwAddCustomVoicePush;

typedef struct _HwAddCustomVoicePush_ObjVoice {
    int32_t voiceId;
    char voicePath[64];
    int32_t voiceType;
    bool has_voiceTime;
    int32_t voiceTime;
    bool has_orderBy;
    int32_t orderBy;
    char netPath[64];
/* @@protoc_insertion_point(struct:HwAddCustomVoicePush_ObjVoice) */
} HwAddCustomVoicePush_ObjVoice;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwAddCustomVoicePush_init_default        {{{NULL}, NULL}}
#define HwAddCustomVoicePush_ObjVoice_init_default {0, {{NULL}, NULL}, 0, false, 0, false, 0, {{NULL}, NULL}}
#define HwAddCustomVoicePush_init_zero           {{{NULL}, NULL}}
#define HwAddCustomVoicePush_ObjVoice_init_zero  {0, {{NULL}, NULL}, 0, false, 0, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwAddCustomVoicePush_objVoice_tag        1
#define HwAddCustomVoicePush_ObjVoice_voiceId_tag 1
#define HwAddCustomVoicePush_ObjVoice_voicePath_tag 2
#define HwAddCustomVoicePush_ObjVoice_voiceType_tag 3
#define HwAddCustomVoicePush_ObjVoice_voiceTime_tag 4
#define HwAddCustomVoicePush_ObjVoice_orderBy_tag 5
#define HwAddCustomVoicePush_ObjVoice_netPath_tag 6

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwAddCustomVoicePush_fields[2];
extern const pb_field_t HwAddCustomVoicePush_ObjVoice_fields[7];

/* Maximum encoded size of messages (where known) */
/* HwAddCustomVoicePush_size depends on runtime parameters */
/* HwAddCustomVoicePush_ObjVoice_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWADDCUSTOMVOICEPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
