/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 20:33:19 2017. */

#ifndef PB_HWADDDISCUSSPUSH_PB_H_INCLUDED
#define PB_HWADDDISCUSSPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwAddDiscussPush {
    int32_t discussId;
    char discussContent[64];
    int32_t createTime;
/* @@protoc_insertion_point(struct:HwAddDiscussPush) */
} HwAddDiscussPush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwAddDiscussPush_init_default            {0, {{NULL}, NULL}, 0}
#define HwAddDiscussPush_init_zero               {0, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwAddDiscussPush_discussId_tag           1
#define HwAddDiscussPush_discussContent_tag      2
#define HwAddDiscussPush_createTime_tag          3

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwAddDiscussPush_fields[4];

/* Maximum encoded size of messages (where known) */
/* HwAddDiscussPush_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWADDDISCUSSPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
