/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon Jul 17 01:36:29 2017. */

#ifndef PB_HWCACHEVOICEPUSH_PB_H_INCLUDED
#define PB_HWCACHEVOICEPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwCacheVoicePush {
    pb_callback_t objVoice;
/* @@protoc_insertion_point(struct:HwCacheVoicePush) */
} HwCacheVoicePush;

typedef struct _HwCacheVoicePush_ObjVoice {
    int32_t voiceId;
    char voicePath[64];
    bool has_voiceType;
    int32_t voiceType;
/* @@protoc_insertion_point(struct:HwCacheVoicePush_ObjVoice) */
} HwCacheVoicePush_ObjVoice;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwCacheVoicePush_init_default            {{{NULL}, NULL}}
#define HwCacheVoicePush_ObjVoice_init_default   {0, {{NULL}, NULL}, false, 0}
#define HwCacheVoicePush_init_zero               {{{NULL}, NULL}}
#define HwCacheVoicePush_ObjVoice_init_zero      {0, {{NULL}, NULL}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwCacheVoicePush_objVoice_tag            1
#define HwCacheVoicePush_ObjVoice_voiceId_tag    1
#define HwCacheVoicePush_ObjVoice_voicePath_tag  2
#define HwCacheVoicePush_ObjVoice_voiceType_tag  3

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwCacheVoicePush_fields[2];
extern const pb_field_t HwCacheVoicePush_ObjVoice_fields[4];

/* Maximum encoded size of messages (where known) */
/* HwCacheVoicePush_size depends on runtime parameters */
/* HwCacheVoicePush_ObjVoice_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWCACHEVOICEPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
