/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Jul 18 19:07:54 2017. */

#ifndef PB_HWCAPACITYPUSH_PB_H_INCLUDED
#define PB_HWCAPACITYPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwCapacityPush {
    int32_t userId;
/* @@protoc_insertion_point(struct:HwCapacityPush) */
} HwCapacityPush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwCapacityPush_init_default              {0}
#define HwCapacityPush_init_zero                 {0}

/* Field tags (for use in manual encoding/decoding) */
#define HwCapacityPush_userId_tag                1

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwCapacityPush_fields[2];

/* Maximum encoded size of messages (where known) */
#define HwCapacityPush_size                      11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWCAPACITYPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
