/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 19:16:57 2017. */

#ifndef PB_HWCHANGENAMEPUSH_PB_H_INCLUDED
#define PB_HWCHANGENAMEPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwChangeNamePush {
    int32_t userId;
    char nickname[64];
/* @@protoc_insertion_point(struct:HwChangeNamePush) */
} HwChangeNamePush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwChangeNamePush_init_default            {0, {{NULL}, NULL}}
#define HwChangeNamePush_init_zero               {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwChangeNamePush_userId_tag              1
#define HwChangeNamePush_nickname_tag            2

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwChangeNamePush_fields[3];

/* Maximum encoded size of messages (where known) */
/* HwChangeNamePush_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWCHANGENAMEPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
