/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Jul 18 22:37:06 2017. */

#ifndef PB_HWCHANGESTATUSREQ_PB_H_INCLUDED
#define PB_HWCHANGESTATUSREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwChangeStatusReq {
    char serialNum[64];
    int32_t state;
    bool has_reqTime;
    int32_t reqTime;
/* @@protoc_insertion_point(struct:HwChangeStatusReq) */
} HwChangeStatusReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwChangeStatusReq_init_default           {{{NULL}, NULL}, 0, false, 0}
#define HwChangeStatusReq_init_zero              {{{NULL}, NULL}, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwChangeStatusReq_serialNum_tag          1
#define HwChangeStatusReq_state_tag              2
#define HwChangeStatusReq_reqTime_tag            3

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwChangeStatusReq_fields[4];

/* Maximum encoded size of messages (where known) */
/* HwChangeStatusReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWCHANGESTATUSREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
