/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 22:22:25 2017. */

#ifndef PB_HWDELETESDVOICEPUSH_PB_H_INCLUDED
#define PB_HWDELETESDVOICEPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwDeleteSDVoicePush {
    pb_callback_t objVoice;
/* @@protoc_insertion_point(struct:HwDeleteSDVoicePush) */
} HwDeleteSDVoicePush;

typedef struct _HwDeleteSDVoicePush_ObjVoice {
    int32_t voiceId;
    char voiceName[64];
/* @@protoc_insertion_point(struct:HwDeleteSDVoicePush_ObjVoice) */
} HwDeleteSDVoicePush_ObjVoice;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwDeleteSDVoicePush_init_default         {{{NULL}, NULL}}
#define HwDeleteSDVoicePush_ObjVoice_init_default {0, {{NULL}, NULL}}
#define HwDeleteSDVoicePush_init_zero            {{{NULL}, NULL}}
#define HwDeleteSDVoicePush_ObjVoice_init_zero   {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwDeleteSDVoicePush_objVoice_tag         1
#define HwDeleteSDVoicePush_ObjVoice_voiceId_tag 1
#define HwDeleteSDVoicePush_ObjVoice_voiceName_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwDeleteSDVoicePush_fields[2];
extern const pb_field_t HwDeleteSDVoicePush_ObjVoice_fields[3];

/* Maximum encoded size of messages (where known) */
/* HwDeleteSDVoicePush_size depends on runtime parameters */
/* HwDeleteSDVoicePush_ObjVoice_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWDELETESDVOICEPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
