/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 22:22:46 2017. */

#ifndef PB_HWDELETEVOICEPUSH_PB_H_INCLUDED
#define PB_HWDELETEVOICEPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwDeleteVoicePush {
    char voiceIds[64];
/* @@protoc_insertion_point(struct:HwDeleteVoicePush) */
} HwDeleteVoicePush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwDeleteVoicePush_init_default           {{{NULL}, NULL}}
#define HwDeleteVoicePush_init_zero              {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwDeleteVoicePush_voiceIds_tag           1

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwDeleteVoicePush_fields[2];

/* Maximum encoded size of messages (where known) */
/* HwDeleteVoicePush_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWDELETEVOICEPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
