/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon Jul 17 01:36:03 2017. */

#ifndef PB_HWDELETECUSTOMVOICEPUSH_PB_H_INCLUDED
#define PB_HWDELETECUSTOMVOICEPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwDeleteCustomVoicePush {
    pb_callback_t objVoice;
/* @@protoc_insertion_point(struct:HwDeleteCustomVoicePush) */
} HwDeleteCustomVoicePush;

typedef struct _HwDeleteCustomVoicePush_ObjVoice {
    int32_t voiceId;
    int32_t voiceType;
/* @@protoc_insertion_point(struct:HwDeleteCustomVoicePush_ObjVoice) */
} HwDeleteCustomVoicePush_ObjVoice;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwDeleteCustomVoicePush_init_default     {{{NULL}, NULL}}
#define HwDeleteCustomVoicePush_ObjVoice_init_default {0, 0}
#define HwDeleteCustomVoicePush_init_zero        {{{NULL}, NULL}}
#define HwDeleteCustomVoicePush_ObjVoice_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwDeleteCustomVoicePush_objVoice_tag     1
#define HwDeleteCustomVoicePush_ObjVoice_voiceId_tag 1
#define HwDeleteCustomVoicePush_ObjVoice_voiceType_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwDeleteCustomVoicePush_fields[2];
extern const pb_field_t HwDeleteCustomVoicePush_ObjVoice_fields[3];

/* Maximum encoded size of messages (where known) */
/* HwDeleteCustomVoicePush_size depends on runtime parameters */
#define HwDeleteCustomVoicePush_ObjVoice_size    22

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWDELETECUSTOMVOICEPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
