/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 23:12:01 2017. */

#ifndef PB_HWDLLOCALTOAPPREQ_PB_H_INCLUDED
#define PB_HWDLLOCALTOAPPREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwDLLocalToAppReq {
    char serialNum[64];
    pb_callback_t objVoice;
/* @@protoc_insertion_point(struct:HwDLLocalToAppReq) */
} HwDLLocalToAppReq;

typedef struct _HwDLLocalToAppReq_ObjVoice {
    int32_t voiceId;
    int32_t dlType;
/* @@protoc_insertion_point(struct:HwDLLocalToAppReq_ObjVoice) */
} HwDLLocalToAppReq_ObjVoice;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwDLLocalToAppReq_init_default           {{{NULL}, NULL}, {{NULL}, NULL}}
#define HwDLLocalToAppReq_ObjVoice_init_default  {0, 0}
#define HwDLLocalToAppReq_init_zero              {{{NULL}, NULL}, {{NULL}, NULL}}
#define HwDLLocalToAppReq_ObjVoice_init_zero     {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwDLLocalToAppReq_serialNum_tag          1
#define HwDLLocalToAppReq_objVoice_tag           2
#define HwDLLocalToAppReq_ObjVoice_voiceId_tag   1
#define HwDLLocalToAppReq_ObjVoice_dlType_tag    2

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwDLLocalToAppReq_fields[3];
extern const pb_field_t HwDLLocalToAppReq_ObjVoice_fields[3];

/* Maximum encoded size of messages (where known) */
/* HwDLLocalToAppReq_size depends on runtime parameters */
#define HwDLLocalToAppReq_ObjVoice_size          22

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWDLLOCALTOAPPREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
