/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Wed Sep 27 17:00:41 2017. */

#ifndef PB_HWDLLOCALSTATUSRESP_PB_H_INCLUDED
#define PB_HWDLLOCALSTATUSRESP_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwDLLocalStatusResp {
    int64_t dledVoiceId;
    pb_callback_t dlingVoice;
    pb_callback_t pauseVoice;
/* @@protoc_insertion_point(struct:HwDLLocalStatusResp) */
} HwDLLocalStatusResp;

typedef struct _HwDLLocalStatusResp_ObjVoice {
    int64_t voiceId;
    char netPath[128];
    char localPath[128];
    bool has_voiceName;
    char voiceName[128];
/* @@protoc_insertion_point(struct:HwDLLocalStatusResp_ObjVoice) */
} HwDLLocalStatusResp_ObjVoice;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwDLLocalStatusResp_init_default         {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define HwDLLocalStatusResp_ObjVoice_init_default {0, "", "", false, ""}
#define HwDLLocalStatusResp_init_zero            {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define HwDLLocalStatusResp_ObjVoice_init_zero   {0, "", "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define HwDLLocalStatusResp_dledVoiceId_tag      1
#define HwDLLocalStatusResp_dlingVoice_tag       2
#define HwDLLocalStatusResp_pauseVoice_tag       3
#define HwDLLocalStatusResp_ObjVoice_voiceId_tag 1
#define HwDLLocalStatusResp_ObjVoice_netPath_tag 2
#define HwDLLocalStatusResp_ObjVoice_localPath_tag 3
#define HwDLLocalStatusResp_ObjVoice_voiceName_tag 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwDLLocalStatusResp_fields[4];
extern const pb_field_t HwDLLocalStatusResp_ObjVoice_fields[5];

/* Maximum encoded size of messages (where known) */
/* HwDLLocalStatusResp_size depends on runtime parameters */
#define HwDLLocalStatusResp_ObjVoice_size        404

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWDLLOCALSTATUSRESP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
