/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Jul 18 19:09:07 2017. */

#ifndef PB_HWGETWIFIPUSH_PB_H_INCLUDED
#define PB_HWGETWIFIPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwGetWifiPush {
    int32_t userId;
/* @@protoc_insertion_point(struct:HwGetWifiPush) */
} HwGetWifiPush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwGetWifiPush_init_default               {0}
#define HwGetWifiPush_init_zero                  {0}

/* Field tags (for use in manual encoding/decoding) */
#define HwGetWifiPush_userId_tag                 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwGetWifiPush_fields[2];

/* Maximum encoded size of messages (where known) */
#define HwGetWifiPush_size                       11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWGETWIFIPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
