/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Wed Sep 27 16:49:04 2017. */

#ifndef PB_HWINFOREQ_PB_H_INCLUDED
#define PB_HWINFOREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwInfoReq {
    char serialNum[128];
/* @@protoc_insertion_point(struct:HwInfoReq) */
} HwInfoReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwInfoReq_init_default                   {""}
#define HwInfoReq_init_zero                      {""}

/* Field tags (for use in manual encoding/decoding) */
#define HwInfoReq_serialNum_tag                  1

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwInfoReq_fields[2];

/* Maximum encoded size of messages (where known) */
#define HwInfoReq_size                           131

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWINFOREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
