/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Jul 18 20:56:41 2017. */

#ifndef PB_HWOPERATESTATUSREQ_PB_H_INCLUDED
#define PB_HWOPERATESTATUSREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwOperateStatusReq {
    char serialNum[64];
    int32_t userId;
    int32_t operateType;
    bool isSuccess;
    bool has_voiceId;
    int32_t voiceId;
    char ext[64];
/* @@protoc_insertion_point(struct:HwOperateStatusReq) */
} HwOperateStatusReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwOperateStatusReq_init_default          {{{NULL}, NULL}, 0, 0, 0, false, 0, {{NULL}, NULL}}
#define HwOperateStatusReq_init_zero             {{{NULL}, NULL}, 0, 0, 0, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwOperateStatusReq_serialNum_tag         1
#define HwOperateStatusReq_userId_tag            2
#define HwOperateStatusReq_operateType_tag       3
#define HwOperateStatusReq_isSuccess_tag         4
#define HwOperateStatusReq_voiceId_tag           5
#define HwOperateStatusReq_ext_tag               6

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwOperateStatusReq_fields[7];

/* Maximum encoded size of messages (where known) */
/* HwOperateStatusReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWOPERATESTATUSREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
