/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 19:49:11 2017. */

#ifndef PB_HWPLAYPUSH_PB_H_INCLUDED
#define PB_HWPLAYPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwPlayPush {
    int32_t voiceId;
/* @@protoc_insertion_point(struct:HwPlayPush) */
} HwPlayPush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwPlayPush_init_default                  {0}
#define HwPlayPush_init_zero                     {0}

/* Field tags (for use in manual encoding/decoding) */
#define HwPlayPush_voiceId_tag                   1

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwPlayPush_fields[2];

/* Maximum encoded size of messages (where known) */
#define HwPlayPush_size                          11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWPLAYPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
