/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 20:33:07 2017. */

#ifndef PB_HWPULLDISCUSSREQ_PB_H_INCLUDED
#define PB_HWPULLDISCUSSREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwPullDiscussReq {
    char serialNum[64];
    bool has_reqTime;
    int32_t reqTime;
/* @@protoc_insertion_point(struct:HwPullDiscussReq) */
} HwPullDiscussReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwPullDiscussReq_init_default            {{{NULL}, NULL}, false, 0}
#define HwPullDiscussReq_init_zero               {{{NULL}, NULL}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwPullDiscussReq_serialNum_tag           1
#define HwPullDiscussReq_reqTime_tag             2

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwPullDiscussReq_fields[3];

/* Maximum encoded size of messages (where known) */
/* HwPullDiscussReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWPULLDISCUSSREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
