/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 20:01:07 2017. */

#ifndef PB_HWPULLVOICELISTREQ_PB_H_INCLUDED
#define PB_HWPULLVOICELISTREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwPullVoiceListReq {
    int32_t page;
    int32_t pageSize;
    int32_t relType;
    char serialNum[64];
    char relId[64];
/* @@protoc_insertion_point(struct:HwPullVoiceListReq) */
} HwPullVoiceListReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwPullVoiceListReq_init_default          {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define HwPullVoiceListReq_init_zero             {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwPullVoiceListReq_page_tag              1
#define HwPullVoiceListReq_pageSize_tag          2
#define HwPullVoiceListReq_relType_tag           3
#define HwPullVoiceListReq_serialNum_tag         4
#define HwPullVoiceListReq_relId_tag             5

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwPullVoiceListReq_fields[6];

/* Maximum encoded size of messages (where known) */
/* HwPullVoiceListReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWPULLVOICELISTREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
