/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 20:01:17 2017. */

#ifndef PB_HWPULLVOICEREQ_PB_H_INCLUDED
#define PB_HWPULLVOICEREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwPullVoiceReq {
    char serialNum[64];
    bool has_reqTime;
    int32_t reqTime;
/* @@protoc_insertion_point(struct:HwPullVoiceReq) */
} HwPullVoiceReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwPullVoiceReq_init_default              {{{NULL}, NULL}, false, 0}
#define HwPullVoiceReq_init_zero                 {{{NULL}, NULL}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwPullVoiceReq_serialNum_tag             1
#define HwPullVoiceReq_reqTime_tag               2

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwPullVoiceReq_fields[3];

/* Maximum encoded size of messages (where known) */
/* HwPullVoiceReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWPULLVOICEREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
