/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Thu Oct  5 20:33:25 2017. */

#ifndef PB_HWPULLVOICERESP_PB_H_INCLUDED
#define PB_HWPULLVOICERESP_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwPullVoiceResp_ObjVoice {
    int64_t voiceId;
    char voicePath[64];
    int64_t createTime;
    bool has_voiceType;
    int64_t voiceType;
/* @@protoc_insertion_point(struct:HwPullVoiceResp_ObjVoice) */
} HwPullVoiceResp_ObjVoice;

typedef struct _HwPullVoiceResp_Result {
    pb_callback_t objVoice;
    int64_t thisReqTime;
/* @@protoc_insertion_point(struct:HwPullVoiceResp_Result) */
} HwPullVoiceResp_Result;

typedef struct _HwPullVoiceResp {
    int64_t state;
    char msg[64];
    bool has_result;
    HwPullVoiceResp_Result result;
/* @@protoc_insertion_point(struct:HwPullVoiceResp) */
} HwPullVoiceResp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwPullVoiceResp_init_default             {0, "", false, HwPullVoiceResp_Result_init_default}
#define HwPullVoiceResp_Result_init_default      {{{NULL}, NULL}, 0}
#define HwPullVoiceResp_ObjVoice_init_default    {0, "", 0, false, 0}
#define HwPullVoiceResp_init_zero                {0, "", false, HwPullVoiceResp_Result_init_zero}
#define HwPullVoiceResp_Result_init_zero         {{{NULL}, NULL}, 0}
#define HwPullVoiceResp_ObjVoice_init_zero       {0, "", 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwPullVoiceResp_ObjVoice_voiceId_tag     1
#define HwPullVoiceResp_ObjVoice_voicePath_tag   2
#define HwPullVoiceResp_ObjVoice_createTime_tag  3
#define HwPullVoiceResp_ObjVoice_voiceType_tag   4
#define HwPullVoiceResp_Result_objVoice_tag      1
#define HwPullVoiceResp_Result_thisReqTime_tag   2
#define HwPullVoiceResp_state_tag                1
#define HwPullVoiceResp_msg_tag                  2
#define HwPullVoiceResp_result_tag               3

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwPullVoiceResp_fields[4];
extern const pb_field_t HwPullVoiceResp_Result_fields[3];
extern const pb_field_t HwPullVoiceResp_ObjVoice_fields[5];

/* Maximum encoded size of messages (where known) */
#define HwPullVoiceResp_size                     (83 + HwPullVoiceResp_Result_size)
/* HwPullVoiceResp_Result_size depends on runtime parameters */
#define HwPullVoiceResp_ObjVoice_size            99

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWPULLVOICERESP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
