/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Wed Sep 27 16:53:45 2017. */

#ifndef PB_HWPULLDISCUSSRESP_PB_H_INCLUDED
#define PB_HWPULLDISCUSSRESP_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwPullDiscussResp {
    pb_callback_t objDiscuss;
    int64_t thisReqTime;
/* @@protoc_insertion_point(struct:HwPullDiscussResp) */
} HwPullDiscussResp;

typedef struct _HwPullDiscussResp_ObjDiscuss {
    int64_t discussId;
    char discussContent[128];
    int64_t createTime;
/* @@protoc_insertion_point(struct:HwPullDiscussResp_ObjDiscuss) */
} HwPullDiscussResp_ObjDiscuss;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwPullDiscussResp_init_default           {{{NULL}, NULL}, 0}
#define HwPullDiscussResp_ObjDiscuss_init_default {0, "", 0}
#define HwPullDiscussResp_init_zero              {{{NULL}, NULL}, 0}
#define HwPullDiscussResp_ObjDiscuss_init_zero   {0, "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwPullDiscussResp_objDiscuss_tag         1
#define HwPullDiscussResp_thisReqTime_tag        2
#define HwPullDiscussResp_ObjDiscuss_discussId_tag 1
#define HwPullDiscussResp_ObjDiscuss_discussContent_tag 2
#define HwPullDiscussResp_ObjDiscuss_createTime_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwPullDiscussResp_fields[3];
extern const pb_field_t HwPullDiscussResp_ObjDiscuss_fields[4];

/* Maximum encoded size of messages (where known) */
/* HwPullDiscussResp_size depends on runtime parameters */
#define HwPullDiscussResp_ObjDiscuss_size        153

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWPULLDISCUSSRESP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
