/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Thu Oct  5 21:41:27 2017. */

#ifndef PB_HWPULLVOICELISTRESP_PB_H_INCLUDED
#define PB_HWPULLVOICELISTRESP_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwPullVoiceListResp {
    int64_t state;
    char msg[64];
    int64_t allCount;
    pb_callback_t objVoice;
/* @@protoc_insertion_point(struct:HwPullVoiceListResp) */
} HwPullVoiceListResp;

typedef struct _HwPullVoiceListResp_ObjVoice {
    int64_t voiceId;
    int64_t voiceType;
    char voicePath[64];
    bool has_createTime;
    int64_t createTime;
    bool has_orderBy;
    int64_t orderBy;
    bool has_netPath;
    char netPath[64];
    bool has_voiceName;
    char voiceName[64];
/* @@protoc_insertion_point(struct:HwPullVoiceListResp_ObjVoice) */
} HwPullVoiceListResp_ObjVoice;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwPullVoiceListResp_init_default         {0, "", 0, {{NULL}, NULL}}
#define HwPullVoiceListResp_ObjVoice_init_default {0, 0, "", false, 0, false, 0, false, "", false, ""}
#define HwPullVoiceListResp_init_zero            {0, "", 0, {{NULL}, NULL}}
#define HwPullVoiceListResp_ObjVoice_init_zero   {0, 0, "", false, 0, false, 0, false, "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define HwPullVoiceListResp_state_tag            1
#define HwPullVoiceListResp_msg_tag              2
#define HwPullVoiceListResp_allCount_tag         3
#define HwPullVoiceListResp_objVoice_tag         4
#define HwPullVoiceListResp_ObjVoice_voiceId_tag 1
#define HwPullVoiceListResp_ObjVoice_voiceType_tag 2
#define HwPullVoiceListResp_ObjVoice_voicePath_tag 3
#define HwPullVoiceListResp_ObjVoice_createTime_tag 4
#define HwPullVoiceListResp_ObjVoice_orderBy_tag 5
#define HwPullVoiceListResp_ObjVoice_netPath_tag 6
#define HwPullVoiceListResp_ObjVoice_voiceName_tag 7

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwPullVoiceListResp_fields[5];
extern const pb_field_t HwPullVoiceListResp_ObjVoice_fields[8];

/* Maximum encoded size of messages (where known) */
/* HwPullVoiceListResp_size depends on runtime parameters */
#define HwPullVoiceListResp_ObjVoice_size        242

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWPULLVOICELISTRESP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
