/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Oct  3 12:29:38 2017. */

#ifndef PB_HWPULLDISCUSSRESP_PB_H_INCLUDED
#define PB_HWPULLDISCUSSRESP_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwPullDiscussResp_ObjDiscuss {
    int64_t discussId;
    char discussContent[64];
    int64_t createTime;
/* @@protoc_insertion_point(struct:HwPullDiscussResp_ObjDiscuss) */
} HwPullDiscussResp_ObjDiscuss;

typedef struct _HwPullDiscussResp_Result {
    pb_callback_t objDiscuss;
    int64_t thisReqTime;
/* @@protoc_insertion_point(struct:HwPullDiscussResp_Result) */
} HwPullDiscussResp_Result;

typedef struct _HwPullDiscussResp {
    int64_t state;
    char msg[64];
    bool has_result;
    HwPullDiscussResp_Result result;
/* @@protoc_insertion_point(struct:HwPullDiscussResp) */
} HwPullDiscussResp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwPullDiscussResp_init_default           {0, "", false, HwPullDiscussResp_Result_init_default}
#define HwPullDiscussResp_Result_init_default    {{{NULL}, NULL}, 0}
#define HwPullDiscussResp_ObjDiscuss_init_default {0, "", 0}
#define HwPullDiscussResp_init_zero              {0, "", false, HwPullDiscussResp_Result_init_zero}
#define HwPullDiscussResp_Result_init_zero       {{{NULL}, NULL}, 0}
#define HwPullDiscussResp_ObjDiscuss_init_zero   {0, "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwPullDiscussResp_ObjDiscuss_discussId_tag 1
#define HwPullDiscussResp_ObjDiscuss_discussContent_tag 2
#define HwPullDiscussResp_ObjDiscuss_createTime_tag 3
#define HwPullDiscussResp_Result_objDiscuss_tag  1
#define HwPullDiscussResp_Result_thisReqTime_tag 2
#define HwPullDiscussResp_state_tag              1
#define HwPullDiscussResp_msg_tag                2
#define HwPullDiscussResp_result_tag             3

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwPullDiscussResp_fields[4];
extern const pb_field_t HwPullDiscussResp_Result_fields[3];
extern const pb_field_t HwPullDiscussResp_ObjDiscuss_fields[4];

/* Maximum encoded size of messages (where known) */
#define HwPullDiscussResp_size                   (83 + HwPullDiscussResp_Result_size)
/* HwPullDiscussResp_Result_size depends on runtime parameters */
#define HwPullDiscussResp_ObjDiscuss_size        88

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWPULLDISCUSSRESP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
