/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Fri Sep  8 02:12:55 2017. */

#ifndef PB_HWREGISTERPUSH_PB_H_INCLUDED
#define PB_HWREGISTERPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwRegisterPush {
    int32_t userId;
    char nickname[20];
    bool has_needReset;
    bool needReset;
/* @@protoc_insertion_point(struct:HwRegisterPush) */
} HwRegisterPush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwRegisterPush_init_default              {0, {{NULL}, NULL}, false, 0}
#define HwRegisterPush_init_zero                 {0, {{NULL}, NULL}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwRegisterPush_userId_tag                1
#define HwRegisterPush_nickname_tag              2
#define HwRegisterPush_needReset_tag             3

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwRegisterPush_fields[4];

/* Maximum encoded size of messages (where known) */
/* HwRegisterPush_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWREGISTERPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
