/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Wed Jul 12 20:38:35 2017. */

#ifndef PB_HWREGISTERREQ_PB_H_INCLUDED
#define PB_HWREGISTERREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwRegisterReq {
    char serialNum[64];
    int32_t userId;
    char nickname[64];
    char desc[64];
    char avatar[64];
/* @@protoc_insertion_point(struct:HwRegisterReq) */
} HwRegisterReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwRegisterReq_init_default               {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define HwRegisterReq_init_zero                  {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwRegisterReq_serialNum_tag              1
#define HwRegisterReq_userId_tag                 2
#define HwRegisterReq_nickname_tag               3
#define HwRegisterReq_desc_tag                   4
#define HwRegisterReq_avatar_tag                 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwRegisterReq_fields[6];

/* Maximum encoded size of messages (where known) */
/* HwRegisterReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWREGISTERREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
