/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Jul 18 19:07:42 2017. */

#ifndef PB_HWSETWIFIPUSH_PB_H_INCLUDED
#define PB_HWSETWIFIPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwSetWifiPush {
    int32_t userId;
    char account[64];
    char password[64];
/* @@protoc_insertion_point(struct:HwSetWifiPush) */
} HwSetWifiPush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwSetWifiPush_init_default               {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define HwSetWifiPush_init_zero                  {0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwSetWifiPush_userId_tag                 1
#define HwSetWifiPush_account_tag                2
#define HwSetWifiPush_password_tag               3

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwSetWifiPush_fields[4];

/* Maximum encoded size of messages (where known) */
/* HwSetWifiPush_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWSETWIFIPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
