/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 22:21:56 2017. */

#ifndef PB_HWSHAREVOICEPUSH_PB_H_INCLUDED
#define PB_HWSHAREVOICEPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwShareVoicePush {
    int32_t voiceId;
    char voicePath[64];
    int32_t shareTime;
    bool has_voiceType;
    int32_t voiceType;
/* @@protoc_insertion_point(struct:HwShareVoicePush) */
} HwShareVoicePush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwShareVoicePush_init_default            {0, {{NULL}, NULL}, 0, false, 0}
#define HwShareVoicePush_init_zero               {0, {{NULL}, NULL}, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwShareVoicePush_voiceId_tag             1
#define HwShareVoicePush_voicePath_tag           2
#define HwShareVoicePush_shareTime_tag           3
#define HwShareVoicePush_voiceType_tag           4

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwShareVoicePush_fields[5];

/* Maximum encoded size of messages (where known) */
/* HwShareVoicePush_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWSHAREVOICEPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
