/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Jul 18 19:08:44 2017. */

#ifndef PB_HWSLEEPMODEPUSH_PB_H_INCLUDED
#define PB_HWSLEEPMODEPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwSleepModePush {
    int32_t sleepMode;
/* @@protoc_insertion_point(struct:HwSleepModePush) */
} HwSleepModePush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwSleepModePush_init_default             {0}
#define HwSleepModePush_init_zero                {0}

/* Field tags (for use in manual encoding/decoding) */
#define HwSleepModePush_sleepMode_tag            1

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwSleepModePush_fields[2];

/* Maximum encoded size of messages (where known) */
#define HwSleepModePush_size                     11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWSLEEPMODEPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
