/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Wed Jul 19 01:54:59 2017. */

#ifndef PB_HWSTATUSTOAPPREQ_PB_H_INCLUDED
#define PB_HWSTATUSTOAPPREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwStatusToAppReq {
    char serialNum[64];
    int32_t userId;
    bool has_voiceId;
    int32_t voiceId;
    bool has_voiceType;
    int32_t voiceType;
    int32_t playMode;
    int32_t volume;
    int32_t status;
    bool has_relType;
    int32_t relType;
    char relId[64];
    bool has_power;
    int32_t power;
    bool has_powerStatus;
    int32_t powerStatus;
    bool has_sleepMode;
    int32_t sleepMode;
    bool has_timing;
    int32_t timing;
/* @@protoc_insertion_point(struct:HwStatusToAppReq) */
} HwStatusToAppReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwStatusToAppReq_init_default            {{{NULL}, NULL}, 0, false, 0, false, 0, 0, 0, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0}
#define HwStatusToAppReq_init_zero               {{{NULL}, NULL}, 0, false, 0, false, 0, 0, 0, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HwStatusToAppReq_serialNum_tag           1
#define HwStatusToAppReq_userId_tag              2
#define HwStatusToAppReq_voiceId_tag             3
#define HwStatusToAppReq_voiceType_tag           4
#define HwStatusToAppReq_playMode_tag            5
#define HwStatusToAppReq_volume_tag              6
#define HwStatusToAppReq_status_tag              7
#define HwStatusToAppReq_relType_tag             8
#define HwStatusToAppReq_relId_tag               9
#define HwStatusToAppReq_power_tag               10
#define HwStatusToAppReq_powerStatus_tag         11
#define HwStatusToAppReq_sleepMode_tag           12
#define HwStatusToAppReq_timing_tag              13

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwStatusToAppReq_fields[14];

/* Maximum encoded size of messages (where known) */
/* HwStatusToAppReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWSTATUSTOAPPREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
