/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Sep 10 03:52:59 2017. */

#ifndef PB_HWTALKBACKOPENPUSH_PB_H_INCLUDED
#define PB_HWTALKBACKOPENPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwTalkbackOpenPush {
    int64_t userId;
    char streamAddress[100];
/* @@protoc_insertion_point(struct:HwTalkbackOpenPush) */
} HwTalkbackOpenPush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwTalkbackOpenPush_init_default          {0, {{NULL}, NULL}}
#define HwTalkbackOpenPush_init_zero             {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwTalkbackOpenPush_userId_tag            1
#define HwTalkbackOpenPush_streamAddress_tag     2

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwTalkbackOpenPush_fields[3];

/* Maximum encoded size of messages (where known) */
/* HwTalkbackOpenPush_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWTALKBACKOPENPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
