/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Jul 18 19:08:19 2017. */

#ifndef PB_HWVERSIONUPDATEPUSH_PB_H_INCLUDED
#define PB_HWVERSIONUPDATEPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwVersionUpdatePush {
    int32_t versionCode;
    char version[64];
/* @@protoc_insertion_point(struct:HwVersionUpdatePush) */
} HwVersionUpdatePush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwVersionUpdatePush_init_default         {0, {{NULL}, NULL}}
#define HwVersionUpdatePush_init_zero            {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwVersionUpdatePush_versionCode_tag      1
#define HwVersionUpdatePush_version_tag          2

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwVersionUpdatePush_fields[3];

/* Maximum encoded size of messages (where known) */
/* HwVersionUpdatePush_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWVERSIONUPDATEPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
