/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sat Sep  9 01:55:19 2017. */

#ifndef PB_HWVOICEERRORINFOREQ_PB_H_INCLUDED
#define PB_HWVOICEERRORINFOREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwVoiceErrorInfoReq {
    int32_t pushUserId;
    int32_t voiceId;
    bool has_voiceType;
    int32_t voiceType;
    bool has_relType;
    int32_t relType;
    char relId[10];
    char error[10];
/* @@protoc_insertion_point(struct:HwVoiceErrorInfoReq) */
} HwVoiceErrorInfoReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwVoiceErrorInfoReq_init_default         {0, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define HwVoiceErrorInfoReq_init_zero            {0, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwVoiceErrorInfoReq_pushUserId_tag       1
#define HwVoiceErrorInfoReq_voiceId_tag          2
#define HwVoiceErrorInfoReq_voiceType_tag        3
#define HwVoiceErrorInfoReq_relType_tag          4
#define HwVoiceErrorInfoReq_relId_tag            5
#define HwVoiceErrorInfoReq_error_tag            6

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwVoiceErrorInfoReq_fields[7];

/* Maximum encoded size of messages (where known) */
/* HwVoiceErrorInfoReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWVOICEERRORINFOREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
