/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Fri Sep  8 04:21:36 2017. */

#ifndef PB_HWVOICEINFOREQ_PB_H_INCLUDED
#define PB_HWVOICEINFOREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwVoiceInfoReq {
    int32_t pushUserId;
    int32_t voiceId;
    bool has_voiceType;
    int32_t voiceType;
    bool has_relType;
    int32_t relType;
    char relId[10];
/* @@protoc_insertion_point(struct:HwVoiceInfoReq) */
} HwVoiceInfoReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwVoiceInfoReq_init_default              {0, 0, false, 0, false, 0, {{NULL}, NULL}}
#define HwVoiceInfoReq_init_zero                 {0, 0, false, 0, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwVoiceInfoReq_pushUserId_tag            1
#define HwVoiceInfoReq_voiceId_tag               2
#define HwVoiceInfoReq_voiceType_tag             3
#define HwVoiceInfoReq_relType_tag               4
#define HwVoiceInfoReq_relId_tag                 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwVoiceInfoReq_fields[6];

/* Maximum encoded size of messages (where known) */
/* HwVoiceInfoReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWVOICEINFOREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
