/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Jul 18 19:07:30 2017. */

#ifndef PB_HWWIFITOAPPREQ_PB_H_INCLUDED
#define PB_HWWIFITOAPPREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HwWifiToAppReq {
    char serialNum[64];
    int32_t userId;
    char account[64];
    char password[64];
/* @@protoc_insertion_point(struct:HwWifiToAppReq) */
} HwWifiToAppReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HwWifiToAppReq_init_default              {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define HwWifiToAppReq_init_zero                 {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define HwWifiToAppReq_serialNum_tag             1
#define HwWifiToAppReq_userId_tag                2
#define HwWifiToAppReq_account_tag               3
#define HwWifiToAppReq_password_tag              4

/* Struct field encoding specification for nanopb */
extern const pb_field_t HwWifiToAppReq_fields[5];

/* Maximum encoded size of messages (where known) */
/* HwWifiToAppReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HWWIFITOAPPREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
