/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Sep 10 03:53:19 2017. */

#ifndef PB_IMTOKENREQ_PB_H_INCLUDED
#define PB_IMTOKENREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ImTokenReq {
    char accid[20];
/* @@protoc_insertion_point(struct:ImTokenReq) */
} ImTokenReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ImTokenReq_init_default                  {{{NULL}, NULL}}
#define ImTokenReq_init_zero                     {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ImTokenReq_accid_tag                     1

/* Struct field encoding specification for nanopb */
extern const pb_field_t ImTokenReq_fields[2];

/* Maximum encoded size of messages (where known) */
/* ImTokenReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define IMTOKENREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
