/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Sep 10 03:53:30 2017. */

#ifndef PB_PUSHADDRESSREQ_PB_H_INCLUDED
#define PB_PUSHADDRESSREQ_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _PushAddressReq {
    char serialNum[16];
/* @@protoc_insertion_point(struct:PushAddressReq) */
} PushAddressReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PushAddressReq_init_default              {{{NULL}, NULL}}
#define PushAddressReq_init_zero                 {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define PushAddressReq_serialNum_tag             1

/* Struct field encoding specification for nanopb */
extern const pb_field_t PushAddressReq_fields[2];

/* Maximum encoded size of messages (where known) */
/* PushAddressReq_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define PUSHADDRESSREQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
