/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Fri Sep  8 03:18:12 2017. */

#ifndef PB_SIGNOFFPUSH_PB_H_INCLUDED
#define PB_SIGNOFFPUSH_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _SignOffPush {
    char dummy_field;
/* @@protoc_insertion_point(struct:SignOffPush) */
} SignOffPush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SignOffPush_init_default                 {0}
#define SignOffPush_init_zero                    {0}

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */
extern const pb_field_t SignOffPush_fields[1];

/* Maximum encoded size of messages (where known) */
#define SignOffPush_size                         0

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SIGNOFFPUSH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
