/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jun 18 19:06:23 2017. */

#ifndef PB_ZYY_SIMPLE_PB_H_INCLUDED
#define PB_ZYY_SIMPLE_PB_H_INCLUDED
#include <protob/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _zyy_PMessage {
    int32_t id;
    bool has_num;
    int32_t num;
    char str[128];
/* @@protoc_insertion_point(struct:zyy_PMessage) */
} zyy_PMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define zyy_PMessage_init_default                {0, false, 0, {{NULL}, NULL}}
#define zyy_PMessage_init_zero                   {0, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define zyy_PMessage_id_tag                      1
#define zyy_PMessage_num_tag                     2
#define zyy_PMessage_str_tag                     3

/* Struct field encoding specification for nanopb */
extern const pb_field_t zyy_PMessage_fields[4];

/* Maximum encoded size of messages (where known) */
/* zyy_PMessage_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SIMPLE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
