/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Jul 16 19:34:30 2017. */

#include "protob/AlterMasterPush.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t AlterMasterPush_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, AlterMasterPush, newMasterId, newMasterId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
