/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Thu Jun 22 20:37:09 2017. */

#include "protob/ConnectResp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ConnectResp_fields[8] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ConnectResp, state, state, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC, OTHER, ConnectResp, msg, state, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC, OTHER, ConnectResp, uuid, msg, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, ConnectResp, masterId, uuid, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC, OTHER, ConnectResp, version, masterId, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, ConnectResp, versionCode, version, 0),
    PB_FIELD(  7, STRING  , REQUIRED, STATIC, OTHER, ConnectResp, nickname, versionCode, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
