/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Thu Jun 22 02:20:39 2017. */

#include "protob/ConnectReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ConnectReq_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC , FIRST, ConnectReq, serialNum, serialNum, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, ConnectReq, isReset, serialNum, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, ConnectReq, versionCode, isReset, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
