/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Jul 12 20:03:02 2017. */

#include "protob/DisconnectReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DisconnectReq_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC, FIRST, DisconnectReq, serialNum, serialNum, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
