/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Jul 12 20:26:22 2017. */

#include "protob/DisconnectResp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DisconnectResp_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DisconnectResp, state, state, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC, OTHER, DisconnectResp, msg, state, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
