/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Jul 16 20:33:19 2017. */

#include "protob/HwAddDiscussPush.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwAddDiscussPush_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwAddDiscussPush, discussId, discussId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC , OTHER, HwAddDiscussPush, discussContent, discussId, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwAddDiscussPush, createTime, discussContent, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
