/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Jul 17 01:35:53 2017. */

#include "protob/HwAddCustomVoicePush.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwAddCustomVoicePush_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, HwAddCustomVoicePush, objVoice, objVoice, &HwAddCustomVoicePush_ObjVoice_fields),
    PB_LAST_FIELD
};

const pb_field_t HwAddCustomVoicePush_ObjVoice_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwAddCustomVoicePush_ObjVoice, voiceId, voiceId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwAddCustomVoicePush_ObjVoice, voicePath, voiceId, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwAddCustomVoicePush_ObjVoice, voiceType, voicePath, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, HwAddCustomVoicePush_ObjVoice, voiceTime, voiceType, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, HwAddCustomVoicePush_ObjVoice, orderBy, voiceTime, 0),
    PB_FIELD(  6, STRING  , REQUIRED, STATIC  , OTHER, HwAddCustomVoicePush_ObjVoice, netPath, orderBy, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
