/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Tue Jul 18 19:08:07 2017. */

#include "protob/HwCapacityToAppReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwCapacityToAppReq_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, HwCapacityToAppReq, serialNum, serialNum, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK  , OTHER, HwCapacityToAppReq, objCapacity, serialNum, &HwCapacityToAppReq_ObjCapacity_fields),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwCapacityToAppReq, userId, objCapacity, 0),
    PB_LAST_FIELD
};

const pb_field_t HwCapacityToAppReq_ObjCapacity_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwCapacityToAppReq_ObjCapacity, type, type, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HwCapacityToAppReq_ObjCapacity, totalCapacity, type, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwCapacityToAppReq_ObjCapacity, remainCapacity, totalCapacity, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
