/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Jul 17 01:36:44 2017. */

#include "protob/HwChangeListOrderPush.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwChangeListOrderPush_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwChangeListOrderPush, relType, relType, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwChangeListOrderPush, relId, relType, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwChangeListOrderPush, allCount, relId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
