/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Tue Jul 18 19:08:31 2017. */

#include "protob/HwClosePush.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwClosePush_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwClosePush, timing, timing, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
