/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Jul 16 22:22:10 2017. */

#include "protob/HwDeleteGroupVoicePush.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwDeleteGroupVoicePush_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC , FIRST, HwDeleteGroupVoicePush, voiceIds, voiceIds, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, HwDeleteGroupVoicePush, objVoice, voiceIds, &HwDeleteGroupVoicePush_ObjVoice_fields),
    PB_LAST_FIELD
};

const pb_field_t HwDeleteGroupVoicePush_ObjVoice_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwDeleteGroupVoicePush_ObjVoice, voiceId, voiceId, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HwDeleteGroupVoicePush_ObjVoice, voiceType, voiceId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
