/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Jul 17 01:36:03 2017. */

#include "protob/HwDeleteCustomVoicePush.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwDeleteCustomVoicePush_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK  , FIRST, HwDeleteCustomVoicePush, objVoice, objVoice, &HwDeleteCustomVoicePush_ObjVoice_fields),
    PB_LAST_FIELD
};

const pb_field_t HwDeleteCustomVoicePush_ObjVoice_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwDeleteCustomVoicePush_ObjVoice, voiceId, voiceId, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HwDeleteCustomVoicePush_ObjVoice, voiceType, voiceId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
