/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Jul 17 01:36:53 2017. */

#include "protob/HwDeleteDownloadedVoicePush.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwDeleteDownloadedVoicePush_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC   , FIRST, HwDeleteDownloadedVoicePush, voiceIds, voiceIds, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK  , OTHER, HwDeleteDownloadedVoicePush, objVoice, voiceIds, &HwDeleteDownloadedVoicePush_ObjVoice_fields),
    PB_LAST_FIELD
};

const pb_field_t HwDeleteDownloadedVoicePush_ObjVoice_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwDeleteDownloadedVoicePush_ObjVoice, voiceId, voiceId, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, HwDeleteDownloadedVoicePush_ObjVoice, voiceType, voiceId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
