/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Jul 16 23:12:01 2017. */

#include "protob/HwDLLocalToAppReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwDLLocalToAppReq_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, HwDLLocalToAppReq, serialNum, serialNum, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK  , OTHER, HwDLLocalToAppReq, objVoice, serialNum, &HwDLLocalToAppReq_ObjVoice_fields),
    PB_LAST_FIELD
};

const pb_field_t HwDLLocalToAppReq_ObjVoice_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwDLLocalToAppReq_ObjVoice, voiceId, voiceId, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HwDLLocalToAppReq_ObjVoice, dlType, voiceId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
