/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Sep 27 17:00:41 2017. */

#include "protob/HwDLLocalStatusResp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwDLLocalStatusResp_fields[4] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, HwDLLocalStatusResp, dledVoiceId, dledVoiceId, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, HwDLLocalStatusResp, dlingVoice, dledVoiceId, &HwDLLocalStatusResp_ObjVoice_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, HwDLLocalStatusResp, pauseVoice, dlingVoice, &HwDLLocalStatusResp_ObjVoice_fields),
    PB_LAST_FIELD
};

const pb_field_t HwDLLocalStatusResp_ObjVoice_fields[5] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, HwDLLocalStatusResp_ObjVoice, voiceId, voiceId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwDLLocalStatusResp_ObjVoice, netPath, voiceId, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, HwDLLocalStatusResp_ObjVoice, localPath, netPath, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, HwDLLocalStatusResp_ObjVoice, voiceName, localPath, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
