/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Sep 27 16:51:39 2017. */

#include "protob/HwInfoResp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwInfoResp_fields[3] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, HwInfoResp, status, status, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwInfoResp, nickName, status, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
