/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Sep 27 16:49:04 2017. */

#include "protob/HwInfoReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwInfoReq_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, HwInfoReq, serialNum, serialNum, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
