/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Tue Jul 18 20:56:41 2017. */

#include "protob/HwOperateStatusReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwOperateStatusReq_fields[7] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC, FIRST, HwOperateStatusReq, serialNum, serialNum, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HwOperateStatusReq, userId, serialNum, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwOperateStatusReq, operateType, userId, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, HwOperateStatusReq, isSuccess, operateType, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, HwOperateStatusReq, voiceId, isSuccess, 0),
    PB_FIELD(  6, STRING  , REQUIRED, STATIC  , OTHER, HwOperateStatusReq, ext, voiceId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
