/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Jul 16 19:49:11 2017. */

#include "protob/HwPlayPush.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwPlayPush_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwPlayPush, voiceId, voiceId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
