/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Jul 16 20:33:07 2017. */

#include "protob/HwPullDiscussReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwPullDiscussReq_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC , FIRST, HwPullDiscussReq, serialNum, serialNum, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HwPullDiscussReq, reqTime, serialNum, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
