/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Jul 16 20:01:07 2017. */

#include "protob/HwPullVoiceListReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwPullVoiceListReq_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwPullVoiceListReq, page, page, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HwPullVoiceListReq, pageSize, page, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwPullVoiceListReq, relType, pageSize, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, HwPullVoiceListReq, serialNum, relType, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, HwPullVoiceListReq, relId, serialNum, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
