/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Thu Oct  5 20:33:25 2017. */

#include "protob/HwPullVoiceResp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwPullVoiceResp_fields[4] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, HwPullVoiceResp, state, state, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwPullVoiceResp, msg, state, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, HwPullVoiceResp, result, msg, &HwPullVoiceResp_Result_fields),
    PB_LAST_FIELD
};

const pb_field_t HwPullVoiceResp_Result_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, HwPullVoiceResp_Result, objVoice, objVoice, &HwPullVoiceResp_ObjVoice_fields),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, HwPullVoiceResp_Result, thisReqTime, objVoice, 0),
    PB_LAST_FIELD
};

const pb_field_t HwPullVoiceResp_ObjVoice_fields[5] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, HwPullVoiceResp_ObjVoice, voiceId, voiceId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwPullVoiceResp_ObjVoice, voicePath, voiceId, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, HwPullVoiceResp_ObjVoice, createTime, voicePath, 0),
    PB_FIELD(  4, INT64   , OPTIONAL, STATIC  , OTHER, HwPullVoiceResp_ObjVoice, voiceType, createTime, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(HwPullVoiceResp, result) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_HwPullVoiceResp_HwPullVoiceResp_Result_HwPullVoiceResp_ObjVoice)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(HwPullVoiceResp, result) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_HwPullVoiceResp_HwPullVoiceResp_Result_HwPullVoiceResp_ObjVoice)
#endif


/* @@protoc_insertion_point(eof) */
