/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Sep 27 16:58:48 2017. */

#include "protob/HwPullVoiceResp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwPullVoiceResp_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, HwPullVoiceResp, objVoice, objVoice, &HwPullVoiceResp_ObjVoice_fields),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, HwPullVoiceResp, thisReqTime, objVoice, 0),
    PB_LAST_FIELD
};

const pb_field_t HwPullVoiceResp_ObjVoice_fields[5] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, HwPullVoiceResp_ObjVoice, voiceId, voiceId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwPullVoiceResp_ObjVoice, voicePath, voiceId, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, HwPullVoiceResp_ObjVoice, shareTime, voicePath, 0),
    PB_FIELD(  4, INT64   , OPTIONAL, STATIC  , OTHER, HwPullVoiceResp_ObjVoice, voiceType, shareTime, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
