/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Sep 27 16:53:45 2017. */

#include "protob/HwPullDiscussResp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwPullDiscussResp_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, HwPullDiscussResp, objDiscuss, objDiscuss, &HwPullDiscussResp_ObjDiscuss_fields),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, HwPullDiscussResp, thisReqTime, objDiscuss, 0),
    PB_LAST_FIELD
};

const pb_field_t HwPullDiscussResp_ObjDiscuss_fields[4] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, HwPullDiscussResp_ObjDiscuss, discussId, discussId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwPullDiscussResp_ObjDiscuss, discussContent, discussId, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, HwPullDiscussResp_ObjDiscuss, createTime, discussContent, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
