/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Tue Oct  3 12:29:38 2017. */

#include "protob/HwPullDiscussResp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwPullDiscussResp_fields[4] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, HwPullDiscussResp, state, state, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwPullDiscussResp, msg, state, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, HwPullDiscussResp, result, msg, &HwPullDiscussResp_Result_fields),
    PB_LAST_FIELD
};

const pb_field_t HwPullDiscussResp_Result_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, HwPullDiscussResp_Result, objDiscuss, objDiscuss, &HwPullDiscussResp_ObjDiscuss_fields),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, HwPullDiscussResp_Result, thisReqTime, objDiscuss, 0),
    PB_LAST_FIELD
};

const pb_field_t HwPullDiscussResp_ObjDiscuss_fields[4] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, HwPullDiscussResp_ObjDiscuss, discussId, discussId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwPullDiscussResp_ObjDiscuss, discussContent, discussId, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, HwPullDiscussResp_ObjDiscuss, createTime, discussContent, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(HwPullDiscussResp, result) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_HwPullDiscussResp_HwPullDiscussResp_Result_HwPullDiscussResp_ObjDiscuss)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(HwPullDiscussResp, result) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_HwPullDiscussResp_HwPullDiscussResp_Result_HwPullDiscussResp_ObjDiscuss)
#endif


/* @@protoc_insertion_point(eof) */
