/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Thu Oct  5 21:41:27 2017. */

#include "protob/HwPullVoiceListResp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwPullVoiceListResp_fields[5] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, HwPullVoiceListResp, state, state, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwPullVoiceListResp, msg, state, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, HwPullVoiceListResp, allCount, msg, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, HwPullVoiceListResp, objVoice, allCount, &HwPullVoiceListResp_ObjVoice_fields),
    PB_LAST_FIELD
};

const pb_field_t HwPullVoiceListResp_ObjVoice_fields[8] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, HwPullVoiceListResp_ObjVoice, voiceId, voiceId, 0),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, HwPullVoiceListResp_ObjVoice, voiceType, voiceId, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, HwPullVoiceListResp_ObjVoice, voicePath, voiceType, 0),
    PB_FIELD(  4, INT64   , OPTIONAL, STATIC  , OTHER, HwPullVoiceListResp_ObjVoice, createTime, voicePath, 0),
    PB_FIELD(  5, INT64   , OPTIONAL, STATIC  , OTHER, HwPullVoiceListResp_ObjVoice, orderBy, createTime, 0),
    PB_FIELD(  6, STRING  , OPTIONAL, STATIC  , OTHER, HwPullVoiceListResp_ObjVoice, netPath, orderBy, 0),
    PB_FIELD(  7, STRING  , OPTIONAL, STATIC  , OTHER, HwPullVoiceListResp_ObjVoice, voiceName, netPath, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
