/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Jul 12 20:38:35 2017. */

#include "protob/HwRegisterReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwRegisterReq_fields[6] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC, FIRST, HwRegisterReq, serialNum, serialNum, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC, OTHER, HwRegisterReq, userId, serialNum, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC, OTHER, HwRegisterReq, nickname, userId, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC, OTHER, HwRegisterReq, desc, nickname, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC, OTHER, HwRegisterReq, avatar, desc, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
