/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Jul 17 01:37:04 2017. */

#include "protob/HwSdVoiceAddReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwSdVoiceAddReq_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, HwSdVoiceAddReq, serialNum, serialNum, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK , OTHER, HwSdVoiceAddReq, objVoice, serialNum, &HwSdVoiceAddReq_ObjVoice_fields),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, HwSdVoiceAddReq, isReset, objVoice, 0),
    PB_LAST_FIELD
};

const pb_field_t HwSdVoiceAddReq_ObjVoice_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwSdVoiceAddReq_ObjVoice, voiceId, voiceId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwSdVoiceAddReq_ObjVoice, voiceName, voiceId, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwSdVoiceAddReq_ObjVoice, voiceLength, voiceName, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
