/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Jul 16 22:21:56 2017. */

#include "protob/HwShareVoicePush.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwShareVoicePush_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwShareVoicePush, voiceId, voiceId, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, HwShareVoicePush, voicePath, voiceId, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwShareVoicePush, shareTime, voicePath, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, HwShareVoicePush, voiceType, shareTime, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
