/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Jul 19 01:54:59 2017. */

#include "protob/HwStatusToAppReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwStatusToAppReq_fields[14] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, HwStatusToAppReq, serialNum, serialNum, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, userId, serialNum, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, voiceId, userId, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, voiceType, voiceId, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, playMode, voiceType, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, volume, playMode, 0),
    PB_FIELD(  7, INT32   , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, status, volume, 0),
    PB_FIELD(  8, INT32   , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, relType, status, 0),
    PB_FIELD(  9, STRING  , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, relId, relType, 0),
    PB_FIELD( 10, INT32   , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, power, relId, 0),
    PB_FIELD( 11, INT32   , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, powerStatus, power, 0),
    PB_FIELD( 12, INT32   , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, sleepMode, powerStatus, 0),
    PB_FIELD( 13, INT32   , REQUIRED, STATIC  , OTHER, HwStatusToAppReq, timing, sleepMode, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
