/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Fri Sep  8 04:21:36 2017. */

#include "protob/HwVoiceInfoReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwVoiceInfoReq_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwVoiceInfoReq, pushUserId, pushUserId, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HwVoiceInfoReq, voiceId, pushUserId, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwVoiceInfoReq, voiceType, voiceId, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, HwVoiceInfoReq, relType, voiceType, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, HwVoiceInfoReq, relId, relType, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
