/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sat Sep  9 01:55:19 2017. */

#include "protob/HwVoiceErrorInfoReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwVoiceErrorInfoReq_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, HwVoiceErrorInfoReq, pushUserId, pushUserId, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HwVoiceErrorInfoReq, voiceId, pushUserId, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, HwVoiceErrorInfoReq, voiceType, voiceId, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, HwVoiceErrorInfoReq, relType, voiceType, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, HwVoiceErrorInfoReq, relId, relType, 0),
    PB_FIELD(  6, STRING  , REQUIRED, STATIC  , OTHER, HwVoiceErrorInfoReq, error, relId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
