/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Tue Jul 18 19:07:30 2017. */

#include "protob/HwWifiToAppReq.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HwWifiToAppReq_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC, FIRST, HwWifiToAppReq, serialNum, serialNum, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC, OTHER, HwWifiToAppReq, userId, serialNum, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC, OTHER, HwWifiToAppReq, account, userId, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC, OTHER, HwWifiToAppReq, password, account, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
