/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Sep 10 03:53:30 2017. */

#include <protob/PushAddressReq.pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PushAddressReq_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC, FIRST, PushAddressReq, serialNum, serialNum, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
