/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Fri Sep  8 03:18:12 2017. */

#include "protob/SignOffPush.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SignOffPush_fields[1] = {
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
