/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Jun 18 19:06:23 2017. */

#include "protob/simple.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t zyy_PMessage_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, zyy_PMessage, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, zyy_PMessage, num, id, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, zyy_PMessage, str, num, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
